inputs:
  host:
    required: true
  username:
    required: true
  ssh-private-key:
    required: true
  branch-name:
    required: false
    default: "main"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    - shell: bash
      run: |
        scp -o StrictHostKeyChecking=no \
          ${{ github.action_path }}/deploy.sh \
          ${{ inputs.username }}@${{ inputs.host }}:/tmp/deploy.sh

    - uses: appleboy/ssh-action@master
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        key: ${{ inputs.ssh-private-key }}
        script_stop: true
        script: |
          chmod +x /tmp/deploy.sh
          /tmp/deploy.sh ${{ github.repository }} ${{ inputs.branch-name }}
          rm /tmp/deploy.sh
